cask_args appdir: "/Applications"
# Install package

#brew "ansible"
brew 'autojump'
brew 'dua-cli'
brew 'fd'
brew 'fzf'
brew "gh"
brew 'git'
brew 'htop'
brew 'httpie'
brew 'hugo'
brew 'jq'
brew 'jc'
brew 'mas'
#brew "ncdu"
brew "ngrok"
brew "nmap"
#brew 'node'
#brew "nvm"
brew 'pgcli'
brew "pv"
brew 'ripgrep'
brew 'rsync'
brew "ruby"
brew 'shellcheck'
brew 'starship'
brew 'thefuck'
brew 'tldr'
#brew "vagrant"
#brew "virtualbox"
brew "watch"
brew "zoxide"

# Casks
cask '1password'
cask '1password/tap/1password-cli'
cask 'brave-browser'
cask 'docker'
cask 'dozer'
cask 'finicky'
cask 'google-chrome'
cask 'iterm2'
cask 'keepassxc'
cask 'maccy'
cask 'monitorcontrol'
cask 'obsidian'
cask 'slack'
cask 'spotify'
cask "the-unarchiver"
